version: "3.9"

services:
  app:
    restart: always
    build:
      context: .
    container_name: drone_deploy_web
    env_file: .env
    ports:
      - "8000:8000"   
    volumes:
      - .:/code
      - static_volume:/code/static/
    command: >
      sh -c "python3 manage.py migrate &&
             gunicorn manage_drones.wsgi:application --bind 0.0.0.0:8000" 
    depends_on:
      - db    
      
      
  db:
    restart: always
    image: postgres:14.0-alpine
    container_name: data_postgresql
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  

  nginx:
    restart: always
    build: ./nginx
    container_name: nginx_web
    volumes:
      - static_volume:/code/static/
    ports:
      - "80:80"
    depends_on:
      - app
      
  
volumes:
  postgres_data: 
  static_volume:

