# Generated by Django 4.1.3 on 2022-12-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='url_image',
            field=models.ImageField(upload_to='medications/images'),
        ),
    ]
