# Generated by Django 4.1.3 on 2022-11-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('model', models.CharField(choices=[('L', 'Lightweight'), ('M', 'Middleweight'), ('C', 'Cruiserweight'), ('H', 'Heavyweight')], max_length=1)),
                ('weigth_limit', models.IntegerField(max_length=500)),
                ('battery_capacity', models.IntegerField()),
                ('state', models.CharField(choices=[('ID', 'IDLE'), ('LO', 'LOADING'), ('LD', 'LOADED'), ('DE', 'DELIVERING'), ('DD', 'DELIVERED'), ('RE', 'RETURNING')], max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
