# Generated by Django 4.1.3 on 2022-12-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='weigth_limit',
            field=models.IntegerField(),
        ),
    ]
