# Generated by Django 4.1.3 on 2022-12-01 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_alter_medication_url_image'),
        ('drones', '0003_drone_medications'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatcherDrone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('total', models.FloatField(blank=True, default=0, editable=False)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drones.drone')),
                ('medications', models.ManyToManyField(to='medications.medication')),
            ],
        ),
    ]
